export default [
  {
    questionId: "1",
    questionType: "singleSelection",
    questionText: "Told me that I wasn't good enough",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "2",
    questionType: "singleSelection",
    questionText: "Kept me from medical care",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "3",
    questionType: "singleSelection",
    questionText: "Followed me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "4",
    questionType: "singleSelection",
    questionText: "Tried to turn my family, friends or children against me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "5",
    questionType: "singleSelection",
    questionText: "Locked me in the bedroom",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "6",
    questionType: "singleSelection",
    questionText: "Slapped me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "7",
    questionType: "singleSelection",
    questionText: "Forced me to have sex",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "8",
    questionType: "singleSelection",
    questionText: "Told me that I was ugly",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "9",
    questionType: "singleSelection",
    questionText: "Tried to keep me from seeing or talking to my family",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "10",
    questionType: "singleSelection",
    questionText: "Threw me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "11",
    questionType: "singleSelection",
    questionText: "Hung around outside my house",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "12",
    questionType: "singleSelection",
    questionText: "Blamed me for causing their violent behaviour",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "13",
    questionType: "singleSelection",
    questionText: "Harassed me over the telephone",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "14",
    questionType: "singleSelection",
    questionText: "Shook me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "15",
    questionType: "singleSelection",
    questionText: "Tried to force me to have sex",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "16",
    questionType: "singleSelection",
    questionText: "Harassed me at work",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "17",
    questionType: "singleSelection",
    questionText: "Pushed, grabbed or shoved me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "18",
    questionType: "singleSelection",
    questionText: "Used a knife or gun or other weapon",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "19",
    questionType: "singleSelection",
    questionText:
      "Became upset if dinner/housework wasn't done when they thought it should be",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "20",
    questionType: "singleSelection",
    questionText: "Told me that I was crazy",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "21",
    questionType: "singleSelection",
    questionText: "Told me that no one would ever want me",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "22",
    questionType: "singleSelection",
    questionText: "Took my wallet and left me stranded",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "23",
    questionType: "singleSelection",
    questionText: "Hit or tried to hit me with something",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "24",
    questionType: "singleSelection",
    questionText: "Did not want me to socialize with my female friends",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "25",
    questionType: "singleSelection",
    questionText: "Put foreign objects in my vagina",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "26",
    questionType: "singleSelection",
    questionText: "Refused to let me work outside the home",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "27",
    questionType: "singleSelection",
    questionText: "Kicked me, bit me or hit me with a fist",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "28",
    questionType: "singleSelection",
    questionText:
      "Tried to convince my friends, family or children that I was crazy",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "29",
    questionType: "singleSelection",
    questionText: "Told me that I was stupid",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },
  {
    questionId: "30",
    questionType: "singleSelection",
    questionText: "Beat me up",
    selectionOptions: [
      { name: "Never", weight: "0" },
      { name: "Only Once", weight: "0.2" },
      { name: "Several Times", weight: "0.4" },
      { name: "Once a month", weight: "0.6" },
      { name: "Once a Week", weight: "0.8" },
      { name: "Daily", weight: "1" },
    ],
  },

  {
    questionId: "31",
    questionType: "slider",
    questionText: "Which of these two factors is more important to YOU?",
    sliderMaxValue: 10,
    sliderMinValue: 0,
    labellist: [
      { index: 0, name: "Very unhealthy or abusive" },
      { index: 1, name: "Somewhat unhealthy" },
      { index: 3, name: "Healthy Relationship" },
    ],
  },
  {
    questionId: "32",
    questionType: "slider",
    questionText: "Which of these two factors is more important to YOU?",
    sliderMaxValue: 10,
    sliderMinValue: 0,
    labellist: [
      { index: 0, name: "Very unhealthy or abusive" },
      { index: 1, name: "Somewhat unhealthy" },
      { index: 3, name: "Healthy Relationship" },
    ],
  },
];
