export default [
  {
    questionId: "1",
    questionType: "singleSelection",
    questionText: "Told me that I wasn't good enough",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "2",
    questionType: "singleSelection",
    questionText: "Kept me from medical care",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "3",
    questionType: "singleSelection",
    questionText: "Followed me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "4",
    questionType: "singleSelection",
    questionText: "Tried to turn my family, friends or children against me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "5",
    questionType: "singleSelection",
    questionText: "Locked me in the bedroom",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "6",
    questionType: "singleSelection",
    questionText: "Slapped me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "7",
    questionType: "singleSelection",
    questionText: "Forced me to have sex",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "8",
    questionType: "singleSelection",
    questionText: "Told me that I was ugly",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "9",
    questionType: "singleSelection",
    questionText: "Tried to keep me from seeing or talking to my family",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "10",
    questionType: "singleSelection",
    questionText: "Threw me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "11",
    questionType: "singleSelection",
    questionText: "Hung around outside my house",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "12",
    questionType: "singleSelection",
    questionText: "Blamed me for causing their violent behaviour",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "13",
    questionType: "singleSelection",
    questionText: "Harassed me over the telephone",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "14",
    questionType: "singleSelection",
    questionText: "Shook me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "15",
    questionType: "singleSelection",
    questionText: "Tried to force me to have sex",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "16",
    questionType: "singleSelection",
    questionText: "Harassed me at work",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "17",
    questionType: "singleSelection",
    questionText: "Pushed, grabbed or shoved me",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "18",
    questionType: "singleSelection",
    questionText: "Used a knife or gun or other weapon",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "19",
    questionType: "singleSelection",
    questionText:
      "Became upset if dinner/housework wasn't done when they thought it should be",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  {
    questionId: "20",
    questionType: "singleSelection",
    questionText: "Told me that I was crazy",
    selectionOptions: [
      { name: "Never" },
      { name: "Only Once" },
      { name: "Several Times" },
      { name: "Once a month" },
      { name: "Once a Week" },
      { name: "Daily" },
    ],
  },
  // {
  //   questionId: "21",
  //   questionType: "slider",
  //   questionText: "Which of these two factors is more important to YOU?",
  //   sliderMaxValue: 10,
  //   sliderMinValue: 0,
  //   labellist: [
  //     { index: 0, name: "Very unhealthy or abusive" },
  //     { index: 1, name: "Somewhat unhealthy" },
  //     { index: 3, name: "Healthy Relationship" },
  //   ],
  // },
  // {
  //   questionId: "22",
  //   questionType: "slider",
  //   questionText: "Which of these two factors is more important to YOU?",
  //   sliderMaxValue: 10,
  //   sliderMinValue: 0,
  //   labellist: [
  //     { index: 0, name: "Very unhealthy or abusive" },
  //     { index: 1, name: "Somewhat unhealthy" },
  //     { index: 3, name: "Healthy Relationship" },
  //   ],
  // },
];
